### ISSUE TITLE
Readme is missing

### ISSUE THREAD

**Issue by BinaryBrain** [fixme-lausanne/mpdwsgi-web#1]
Hey,
You should create a README.md file so every member of fixme-lausanne can know what's the purpose of this repo.

**Comment by esc** [comment]
please submit a pull-request.

**Comment by gcmalloc** [comment]
Adressed by #2

**Comment by dgellow** [comment]
![](http://www.troll.me/images/y-u-no/people-y-u-so-impatient.jpg)

**Comment by BinaryBrain** [comment]
![Y U NO MERGE](http://cdn.meme.am/instances/500x/59358733.jpg)
