### ISSUE TITLE
Not loading

### ISSUE THREAD

**Issue by crazygolem** [fixme-lausanne/mpdwsgi-web#5]
The message "Welcome! Please, take a seat while we are loading everything." is displayed non-stop along with the loading animation and never disappears on https://mpd.fixme.ch.
If there are some requirements on the browser side it should be stated somewhere.

I tested with the following browsers on Archlinux:
- Firefox v. 39.0
- Chromium 43.0.2357.130 (Build de développement) (64 bits)

**Comment by dgellow** [comment]
It's a configuration issue on foo, nothing related to your browser.

**Comment by crazygolem** [comment]
Maybe you could leave the issue open until the problem is solved?
And/or explain what the issue is so we can fix it? (or stop worrying about it)

**Comment by dgellow** [comment]
The server wasn't running. It is  now.
